Repository resistance2/travely, pull requests merged in 2024-10, with the labels that each got.

#4 feat: 라우터, 레이아웃, 서버 파일 추가 (#2)
  byul.config.json
  server/.eslintrc.cjs
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/domains/.gitkeep
  server/src/midlewares/.gitkeep
  server/src/utils/.gitkeep
  src/App.tsx
  src/api/.gitkeep
  src/assets/google.png
  src/hooks/.gitkeep
  src/layouts/ContainerLayout.tsx
  src/layouts/Main.tsx
  src/pages/Home.tsx
  src/routes/router.tsx
  src/stores/.gitkeep
  src/styles/theme.ts
Labels: feat

#7 setting/server init 5
  package-lock.json
  server/bun.lockb
  server/package-lock.json
  server/package.json
  server/src/api/.gitkeep
  server/src/app.ts
  server/src/db/.gitkeep
  src/layouts/ContainerLayout.tsx
Labels: setting

#10 [feat] 서버 mongoDB 세팅, 기본 schemase 세팅 했습니다.
  .github/ISSUE_TEMPLATE/feat.yml
  .github/PULL_REQUEST_TEMPLATE.md
  server/bun.lockb
  server/package.json
  server/src/app.ts
  server/src/db/.gitkeep
  server/src/db/connect.ts
  server/src/db/schemas/user.schema.ts
Labels: feat

#15 [feat] AWS S3 이미지 업로드 구현 + CloudFront 연동
  server/bun.lockb
  server/package.json
  server/src/1.jpeg
  server/src/api/.gitkeep
  server/src/api/routes/image.routes.ts
  server/src/app.ts
  server/src/db/schemas/user.schema.ts
  server/src/utils/.gitkeep
  server/src/utils/imageUpload.ts
Labels: feat

#17 [feat] server폴더 ci/cd 배포 workflow 구축(#16)
  .github/workflows/server_cicd.yml
  server/ecosystem.config.js
  server/package.json
  server/src/app.ts
Labels: feat

#20 [Feat] 카드컴포넌트 UI 구현
  .eslintrc.cjs
  .github/.gitmessage.txt
  .husky/pre-commit
  src/ utils/formatCurrency.ts
  src/assets/tag-culture.webp
  src/assets/tag-etc.webp
  src/assets/tag-festival.webp
  src/assets/tag-food.webp
  src/assets/tag-healing.webp
  src/assets/tag-jeju.webp
  src/assets/tag-kdrama.jpg
  src/assets/tag-kdrama.webp
  src/assets/tag-kpop.webp
  src/assets/tag-nature.webp
  src/assets/tag-sports.webp
  src/assets/thumb.png
  src/components/Card.tsx
  src/components/Price.tsx
  src/components/Rating.tsx
  src/components/Tags.tsx
  src/components/home/CardWrap.tsx
  src/components/sub/TagCardWrap.tsx
  src/types/tagType.ts
Labels: design, feat

#24 fix: ?uril -> util (#23)
  src/components/Price.tsx
  src/utils/formatCurrency.ts
Labels: feat

#11 [design] 관리페이지 1차 퍼블리싱
  .husky/pre-commit
  server/package-lock.json
  src/assets/basicProfile.png
  src/components/BorderBtn.tsx
  src/components/FiledBtn.tsx
  src/components/Profile.tsx
  src/components/manageMyTravel/CompletedTrip.tsx
  src/components/manageMyTravel/OngoingTrip.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/data/travelMockData.ts
  src/pages/ManageMyTravel.tsx
  src/routes/router.tsx
  src/types/travelDataType.ts
Labels: design

#26 [Design] 홈, 레이아웃 중간공유
  src/assets/jeju.png
  src/assets/logo-white.png
  src/assets/logo.png
  src/components/travelList/TagCardWrap.tsx
  src/hooks/useHeaderWithVisual.tsx
  src/layouts/ContainerLayout.tsx
  src/layouts/Header.tsx
  src/layouts/HeaderWithVisual.tsx
  src/layouts/Main.tsx
  src/layouts/Visual.tsx
  src/pages/Home.tsx
  src/pages/TravelList.tsx
  src/routes/router.tsx
  src/stores/headerStore.tsx
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
Labels: design

#32 [feat] 팀 컴포넌트 UI구현
  src/components/Tags.tsx
  src/components/Team.tsx
Labels: design, feat

#33 feat: 마이페이지 사이드바 컴포넌트 (#28)
  src/components/myPage/MyPageContainer.tsx
  src/components/myPage/MyPageSideMenu.tsx
  src/routes/router.tsx
  src/styles/theme.ts
Labels: feat

#34 [design] 여행작성페이지 퍼블리싱(#27)
  src/components/FiledBtn.tsx
  src/components/GrayBack.tsx
  src/components/addTravel/ChoiceTags.tsx
  src/components/addTravel/Details.tsx
  src/components/addTravel/Introduction.tsx
  src/components/addTravel/Thumbnail.tsx
  src/pages/AddTravel.tsx
  src/routes/router.tsx
Labels: design

#38 [Design] 내여행 1차 퍼블리싱
  src/components/MyTravel/MyTravelCard.tsx
  src/components/MyTravel/MyTravelContent.tsx
  src/components/MyTravel/MyTravelTab.tsx
  src/components/myPage/MyPageContainer.tsx
Labels: design

#40 fix: MyTravel -> myTravel로 수정
  src/components/myTravel/MyTravelCard.tsx
  src/components/myTravel/MyTravelContent.tsx
  src/components/myTravel/MyTravelTab.tsx
  src/pages/MyTravelList.tsx
  tsconfig.json
Labels: fix

#39 feat: 리뷰 컴포넌트, 마이페이지리뷰 추가 (#29)
  src/assets/reviewImg.png
  src/components/BorderBtn.tsx
  src/components/DeleteIcon.tsx
  src/components/Rating.tsx
  src/components/ReviewCard.tsx
  src/pages/MyReviews.tsx
  src/routes/router.tsx
  src/types/reviewType.ts
Labels: design, feat

#41 [feature]필드추가 및 삭제 기능구현(#35)
  src/components/GrayBack.tsx
  src/components/addTravel/Details.tsx
  src/components/addTravel/DetailsList.tsx
  src/components/addTravel/Introduction.tsx
  src/pages/AddTravel.tsx
  src/stores/useFieldStore.ts
Labels: feat

#42 [feat] 상세 페이지 1차 퍼블리싱
  src/assets/check.png
  src/assets/kt.jpg
  src/assets/map.png
  src/assets/remove.png
  src/components/travelDetail/MoreBtn.tsx
  src/components/travelDetail/SideContainerHeader.tsx
  src/components/travelDetail/SideTravelTeam.tsx
  src/pages/TravelDetail.tsx
  src/routes/router.tsx
Labels: feat

#46 [design]글 작성 페이지 이용안내 및 플로팅메뉴 추가
  src/components/addTravel/Details.tsx
  src/components/addTravel/FloatingMenu.tsx
  src/pages/AddTravel.tsx
  src/stores/useFieldStore.ts
Labels: design

#45 [feat]여행코스 추가 및 삭제 컴포넌트 추가(#44)
  src/components/addTravel/Course.tsx
  src/components/addTravel/Details.tsx
  src/components/addTravel/DetailsList.tsx
  src/pages/AddTravel.tsx
  src/stores/useFieldStore.ts
Labels: feat

#47 feat 리뷰 작성 모달 생성(#30)
  package-lock.json
  package.json
  src/assets/defaultProfile.jpg
  src/components/FileUpload.tsx
  src/components/FiledBtn.tsx
  src/components/Modal.tsx
  src/components/ReviewWriteModal.tsx
  src/components/StarRating.tsx
  src/components/UserProfile.tsx
  src/pages/MyReviews.tsx
  src/styles/GlobalStyles.tsx
Labels: feat

#48 [design] 홈, 레이아웃, 리스트 퍼블리싱
  package-lock.json
  package.json
  src/components/TagCardWrap.tsx
  src/components/TravelCard.tsx
  src/components/home/CardWrap.tsx
  src/components/sub/TagCardWrap.tsx
  src/components/travelList/TagCardWrap.tsx
  src/data/tagDatas.ts
  src/hooks/useHeaderWithVisual.tsx
  src/layouts/Breadcrumb.tsx
  src/layouts/Header.tsx
  src/layouts/HeaderWithVisual.tsx
  src/layouts/Main.tsx
  src/layouts/Visual.tsx
  src/pages/Home.tsx
  src/pages/TravelList.tsx
  src/routes/router.tsx
  src/types/tagType.ts
Labels: design, feat

#50 [Design] 헤더 로그인영역 UI구현, 홈 스와이퍼 css수정, 알람뱃지추가
  src/assets/logo-black.png
  src/components/AlarmBadge.tsx
  src/components/TagCardWrap.tsx
  src/components/TravelCard.tsx
  src/layouts/ Auth.tsx
  src/layouts/Breadcrumb.tsx
  src/layouts/ContainerLayout.tsx
  src/layouts/Header.tsx
  src/layouts/HeaderWithVisual.tsx
  src/layouts/Logo.tsx
  src/layouts/Nav.tsx
  src/layouts/Visual.tsx
  src/pages/Home.tsx
  src/pages/TravelList.tsx
  src/stores/headerStore.tsx
  src/utils/ScrollToTop.tsx
Labels: design

#51 fix 후기 작성 모달 수정
  src/components/FileUploadBtn.tsx
  src/components/FiledBtn.tsx
  src/components/Modal.tsx
  src/components/ReviewWriteModal.tsx
  src/components/StarRating.tsx
  src/components/travelDetail/SideContainerHeader.tsx
Labels: feat

#56 [feat] 썸네일,퀼노트,태그선택 기능 작업(#52)
  package-lock.json
  package.json
  src/components/addTravel/ChoiceTags.tsx
  src/components/addTravel/Introduction.tsx
  src/components/addTravel/Thumbnail.tsx
  src/pages/AddTravel.tsx
  src/types/tagType.ts
Labels: feat

#57 fix: husk에서 lefthook으로 변경, 타입검사 workflow추가
  .eslintrc.cjs
  .husky/pre-commit
  lefthook.yml
  package-lock.json
  package.json
  src/components/myPage/MyPageContainer.tsx
  src/components/travelDetail/MoreBtn.tsx
  src/components/travelDetail/SideTravelTeam.tsx
  src/layouts/ContainerLayout.tsx
  src/layouts/Header.tsx
  src/layouts/HeaderWithVisual.tsx
  src/pages/TravelDetail.tsx
  src/pages/TravelList.tsx
  tsconfig.json
Labels: fix

#64 [fix]오버레이 더 잘보이게 수정
  src/components/addTravel/DetailsList.tsx
  src/components/addTravel/ScheduleTeam.tsx
  src/components/myTravel/MyTravelCard.tsx
  src/stores/useFieldStore.ts
Labels: fix

#65 [feat] 맥 유저를 위해 파일명에 특수문자 검사 추가 했습니다
  lefthook.yml
  package-lock.json
  package.json
Labels: feat

#69 [design] 관리페이지 퍼블리싱 완료
  package-lock.json
  package.json
  src/components/ReviewWriteModal.tsx
  src/components/Team.tsx
  src/components/manageMyTravel/CompletedTravel.tsx
  src/components/manageMyTravel/CompletedTrip.tsx
  src/components/manageMyTravel/MultiPagination.tsx
  src/components/manageMyTravel/OngoingTravel.tsx
  src/components/manageMyTravel/OngoingTrip.tsx
  src/components/manageMyTravel/TravelManageHeader.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/components/myPage/MyPageSideMenu.tsx
  src/components/travelDetail/SideContainerHeader.tsx
  src/data/travelMockData.ts
  src/main.tsx
  src/pages/ManageMyTravel.tsx
  src/stores/usePageStore.ts
  src/styles/theme.ts
  src/types/travelDataType.ts
  src/utils/teamDataFilter.ts
Labels: design, feat

#71 remove: server 폴더 삭제 (#63)
  .github/workflows/server_cicd.yml
  server/.eslintrc.cjs
  server/.prettierignore
  server/.prettierrc
  server/bun.lockb
  server/ecosystem.config.js
  server/package-lock.json
  server/package.json
  server/src/1.jpeg
  server/src/api/routes/image.routes.ts
  server/src/app.ts
  server/src/db/connect.ts
  server/src/db/schemas/user.schema.ts
  server/src/utils/imageUpload.ts
  server/tsconfig.json
  server/tsconfig.tsbuildinfo
Labels: fix

#74 feat: 무한스크롤 기능구현 # 67
  package-lock.json
  package.json
  src/api/cardData.ts
  src/pages/TravelList.tsx
Labels: feat

#75 [Feat] 브레드크럼 추가(내가 만든 여행, 참여한 여행, 여행 상세)
  src/components/TravelCard.tsx
  src/layouts/Breadcrumb.tsx
Labels: feat

#76 [Feat] 스켈레톤 기능구현
  src/components/BorderBtn.tsx
  src/components/Price.tsx
  src/components/SkeletonTravelCard.tsx
  src/components/TagCardWrap.tsx
  src/components/TravelCard.tsx
  src/data/travelCardMockData.ts
  src/layouts/ContainerLayout.tsx
  src/pages/TravelList.tsx
  src/utils/ScrollToTop.tsx
  src/utils/scrollToTop.ts
Labels: design, feat

#79 feat: db스키마 파일 업로드 schema.ts
  src/types/schema.ts
Labels: feat

#78 [feat] pagination작업완료
  src/components/manageMyTravel/CompletedTravel.tsx
  src/components/manageMyTravel/MultiPagination.tsx
  src/components/manageMyTravel/TravelTeam.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/pages/ManageMyTravel.tsx
  src/stores/usePageStore.ts
Labels: feat

#80 [feat] 내 여행 페이지 내가 만든여행 1차
  src/components/myTravel/MyCreatedContent.tsx
  src/components/myTravel/MyTravelTab.tsx
  src/components/myTravel/UserInfo.tsx
  src/pages/MyCreatedTravel.tsx
  src/pages/MyTravelList.tsx
  src/routes/router.tsx
  src/stores/useTabStore.ts
  src/types/schema.ts
Labels: design, feat

#82 fix: import문 경로 수정, 리뷰(수정)모달 수정
  .github/hooks/byulBash.sh
  src/components/Modal.tsx
  src/components/ReviewWriteModal.tsx
  src/components/myPage/MyPageContainer.tsx
  src/components/myTravel/MyTravelTab.tsx
  src/pages/MyCreatedTravel.tsx
  src/stores/.gitkeep
Labels: fix

#83 [feat] 페이지네이션 기능 수정 및 목데이터,타입 수정
  src/components/manageMyTravel/MultiPagination.tsx
  src/components/manageMyTravel/TravelTeam.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/components/myTravel/MyCreatedContent.tsx
  src/data/travelMockData.ts
  src/types/travelDataType.ts
Labels: feat

#86 [feat] 목데이터 추가 및 각 상태에 따른 ui 처리
  src/components/myTravel/MyCreatedContent.tsx
  src/components/myTravel/MyTravelCard.tsx
  src/components/myTravel/MyTravelContent.tsx
  src/data/travelMyCreateMockData.ts
  src/data/travelMyJoinedMockData.ts
Labels: docs

#89 [Feat] 로그인 기능 구현 및 모달 퍼블리싱
  package-lock.json
  package.json
  src/assets/google-icon.svg
  src/assets/kakao-icon.svg
  src/assets/logo-black.png
  src/components/FiledBtn.tsx
  src/firebase.ts
  src/layouts/Auth.tsx
  src/pages/MyAccount.tsx
  src/routes/router.tsx
  src/stores/useLoginStore.ts
  src/stores/useModalStore.ts
  src/vite-env.d.ts
  tsconfig.json
Labels: design, feat

#88 [feat] 여행 소개 첨부이미지 4개로 제한 및 업로드된 링크 받아오기
  src/components/addTravel/FloatingMenu.tsx
  src/components/addTravel/Introduction.tsx
  src/components/addTravel/Thumbnail.tsx
  src/hooks/useImageUpload.ts
  src/pages/AddTravel.tsx
  src/stores/useImageStore.ts
Labels: feat

#91 [Feat]+, - 버튼을 통한 섹션 추가 및 제거
  src/components/addTravel/FloatingMenu.tsx
  src/pages/AddTravel.tsx
Labels: feat

#95 fix: 이미지 주소 수정, eslint 에러난 부분들 수정
  .coderabbit.yaml
  src/assets/guide.jpg
  src/components/ReviewWriteModal.tsx
  src/components/UserProfile.tsx
  src/components/addTravel/FloatingMenu.tsx
  src/components/myTravel/MyCreatedContent.tsx
  src/data/tagDatas.ts
  src/data/travelCardMockData.ts
  src/data/travelMyJoinedMockData.ts
  src/layouts/Auth.tsx
  src/pages/AddTravel.tsx
  src/pages/MyAccount.tsx
  src/pages/TravelList.tsx
Labels: setting

#96 fix: import 경로 이미지로 모두 수정 (#93)
  src/layouts/Auth.tsx
  src/layouts/Logo.tsx
  src/pages/Bookmark.tsx
  src/pages/Home.tsx
Labels: setting

#98 [feat] 관리페이지 route수정 & API요청 hook 작성
  src/components/myPage/MyPageContainer.tsx
  src/hooks/useManageTravelData.ts
  src/layouts/Auth.tsx
  src/layouts/Breadcrumb.tsx
  src/pages/ManageMyTravel.tsx
  src/pages/MyCreatedTravel.tsx
  src/routes/router.tsx
Labels: feat

#99 [Feat] 홈(함께 떠나요NEW) API 연동
  src/components/Price.tsx
  src/components/TravelCard.tsx
  src/data/travelCardMockData.ts
  src/pages/Bookmark.tsx
  src/pages/Home.tsx
  src/pages/TravelList.tsx
  src/types/travelCardType.ts
Labels: feat

#100 [feat] "만나는장소"에도 이미지업로드기능추가
  src/components/addTravel/Details.tsx
  src/components/addTravel/Thumbnail.tsx
  src/layouts/Auth.tsx
  src/pages/AddTravel.tsx
  src/stores/useImageStore.ts
Labels: feat
