Repository resistance2/travely, pull requests merged in 2024-12, with the labels that each got.

#116 [Rename] hooks하위 custom, query로 분리 (#115)
  src/hooks/.gitkeep
  src/hooks/custom/useHandleImageUpload.tsx
  src/hooks/custom/useHeaderWithVisual.tsx
  src/hooks/query/useGetImageUrls.ts
  src/hooks/query/useManageTravelData.ts
  src/layouts/Main.tsx
  src/pages/AddForFindGuide.tsx
  src/pages/AddTravel.tsx
Labels: rename

#118 [FIx] 수정된 api 명세서에 맞게 목데이터, type, props 수정
  src/components/manageMyTravel/MultiPagination.tsx
  src/components/manageMyTravel/TravelTeam.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/data/travelMockData.ts
  src/pages/ManageMyTravel.tsx
  src/stores/usePageStore.ts
  src/types/travelDataType.ts
  src/utils/teamDataFilter.ts
Labels: fix

#120 [Feat] 관리 페이지 api연동
  src/api/.gitkeep
  src/api/addTravel/getImageUrls.ts
  src/api/manageTravel/getManageTravel.ts
  src/api/manageTravel/getManageTravelTeams.ts
  src/components/Price.tsx
  src/components/Profile.tsx
  src/components/manageMyTravel/MultiPagination.tsx
  src/components/manageMyTravel/TravelManageHeader.tsx
  src/components/manageMyTravel/TravelTeam.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/constants/countPerPage.ts
  src/constants/queyKey.ts
  src/data/travelMockData.ts
  src/hooks/query/useGetImageUrls.ts
  src/hooks/query/useGetManageTravel.ts
  src/hooks/query/useGetManageTravelTeams.ts
  src/pages/ManageMyTravel.tsx
  src/styles/theme.ts
  src/types/travelDataType.ts
  src/utils/format.ts
  src/utils/teamDataFilter.ts
  tsconfig.json
Labels: feat

#122 [Refactor] 컴포넌트 폴더 정리
  src/components/findGuideList/GuideCard.tsx
  src/components/myFindGuide/FindGuideCard.tsx
  src/components/myFindGuide/FindGuideContent.tsx
  src/components/myReview/ReviewCard.tsx
  src/components/myReview/ReviewWriteModal.tsx
  src/components/traveList/TravelCard.tsx
  src/pages/Bookmark.tsx
  src/pages/FindGuide.tsx
  src/pages/Home.tsx
  src/pages/MyFindGuide.tsx
  src/pages/MyReviews.tsx
  src/pages/TravelList.tsx
Labels: refactor

#126 [Feature] 로그인 후 _id값 저장 (#125)
  src/layouts/Auth.tsx
  src/types/userType.ts
Labels: feat

#130 [Feat] 별점Rating 컴포넌트 크기 옵션 수정
  .github/ISSUE_TEMPLATE/feat.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  .github/hooks/byulBash.sh
  .github/hooks/commitlint.sh
  lefthook.yml
  src/components/Rating.tsx
  src/components/UserProfile.tsx
  src/components/myReview/ReviewCard.tsx
  src/components/myReview/ReviewWriteModal.tsx
  src/components/myTravel/MyCreatedContent.tsx
  src/components/myTravel/MyTravelCard.tsx
  src/components/traveList/TravelCard.tsx
  src/components/travelDetail/SideContainerHeader.tsx
  src/data/travelMyJoinedMockData.ts
  src/pages/MyReviews.tsx
  src/pages/TravelDetail.tsx
  src/types/reviewType.ts
  src/utils/dataToString.ts
  src/utils/validCheck.ts
Labels: fix, setting

#132 [Feat] 여행자구해요 상세페이지 컴포넌트 분리 및 추가
  src/components/GrayBack.tsx
  src/components/detail/Introduction.tsx
  src/components/detail/MoreBtn.tsx
  src/components/detail/Thumbnail.tsx
  src/components/detail/Title.tsx
  src/components/travelDetail/FAQ.tsx
  src/components/travelDetail/SideContainerHeader.tsx
  src/components/travelDetail/SideTravelTeam.tsx
  src/components/travelDetail/TravelInformation.tsx
  src/hooks/custom/useAccordion.ts
  src/hooks/custom/useMoreBtn.ts
  src/pages/TravelDetail.tsx
Labels: feat

#134 [settins] eslint 설정 변경, 훅 스크립트 type-check 삭제
  .eslintrc.cjs
  .github/hooks/measure-time.ps1
  .github/workflows/type-check.yml
  .prettierrc
  lefthook.yml
  package-lock.json
  package.json
Labels: docs, fix, setting

#136 [Feat] 여행 디테일에 리뷰 리스트 추가 #129
  .eslintrc.cjs
  src/components/GuideProfile.tsx
  src/components/Rating.tsx
  src/components/myReview/ReviewCard.tsx
  src/components/myReview/ReviewWriteModal.tsx
  src/components/myTravel/MyCreatedContent.tsx
  src/components/travelDetail/SideContainerHeader.tsx
  src/components/travelDetail/TravelInformation.tsx
  src/pages/MyReviews.tsx
  src/pages/TravelDetail.tsx
  src/types/reviewType.ts
  src/utils/validCheck.ts
Labels: feat

#137 [Feat]내가 만든 여행 api 연동
  src/api/myCreatedTravel/getMycreatedTravel.ts
  src/api/myCreatedTravel/updateTravelActiveStatus.ts
  src/components/myFindGuide/FindGuideContent.tsx
  src/components/myTravel/MyTravelCard.tsx
  src/components/myTravel/MyTravelContent.tsx
  src/hooks/query/useGetMyCreatedTravel.ts
  src/hooks/query/useUpdateTravelStatus.ts
  src/types/myCreatedTravelType.ts
  src/utils/formatDate.ts
Labels: feat

#142 [Fix] lefthook 수정
  .github/hooks/commitlint.sh
  README.md
  lefthook.yml
  package.json
Labels: fix

#144 [Fix] 커스텀훅 내부 ref 제네릭타입 적용
  src/components/detail/Introduction.tsx
  src/components/travelDetail/TravelInformation.tsx
  src/hooks/custom/useMoreBtn.ts
Labels: feat, fix

#146 [Feat] 여행 관리페이지 활성화 여부 기능 추가
  src/components/manageMyTravel/TravelManageHeader.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/constants/queyKey.ts
  src/hooks/query/useGetMyCreatedTravel.ts
  src/hooks/query/useManageTravelData.ts
  src/hooks/query/useUpdateTravelStatus.ts
  src/pages/ManageMyTravel.tsx
Labels: feat
