Repository resistance2/travely, pull requests merged in 2025-01, with the labels that each got.

#148 [Feat] 내가 만든 여행 api 연동
  src/api/myJoinedTravel/getMyJoinedTravel.ts
  src/components/Team.tsx
  src/components/myFindGuide/FindGuideContent.tsx
  src/components/myTravel/MyJoinedContent.tsx
  src/components/myTravel/MyTravelContent.tsx
  src/constants/queyKey.ts
  src/hooks/query/useGetMyJoinedTravel.ts
  src/pages/MyTravelList.tsx
  src/types/myJoinedTravel.ts
Labels: feat

#147 [Feat]: 홈 화면 (함께 떠나요, 가이드 찾아요) api연동
  README.md
  src/components/Team.tsx
  src/components/findGuideList/GuideCard.tsx
  src/components/traveList/TravelCard.tsx
  src/data/guideCardMockData.ts
  src/data/travelCardMockData.ts
  src/pages/Home.tsx
  src/types/guideCardType.ts
  src/types/travelCardType.ts
Labels: feat

#155 [Feat] Confirm모달 추가 및 적용
  src/components/BorderBtn.tsx
  src/components/ConfirmModal.tsx
  src/components/Modal.tsx
  src/components/manageMyTravel/TravelManageHeader.tsx
  src/constants/modalId.ts
  src/layouts/Auth.tsx
Labels: feat

#156 [Fix] 여행자구해요 글작성 페이지 오류 해결 및 useFieldStore 수정
  src/components/addTravel/ChoiceTags.tsx
  src/components/addTravel/Course.tsx
  src/components/addTravel/Details.tsx
  src/components/addTravel/DetailsList.tsx
  src/components/addTravel/ScheduleTeam.tsx
  src/hooks/custom/useComposing.ts
  src/stores/useFieldStore.ts
  src/types/tagType.ts
Labels: fix

#165 [Feat] 토스트 컴포넌트
  package-lock.json
  package.json
  src/components/Toast.tsx
  src/pages/MyCreatedTravel.tsx
Labels: feat

#166 [Design] toast 색상 변경
  src/components/Toast.tsx
  src/pages/MyCreatedTravel.tsx
Labels: design

#168 [Feat] 신청한 유저 상태변경 api 및 재확인모달 적용
  src/api/manageTravel/patchUserStatus.ts
  src/components/ConfirmModal.tsx
  src/components/manageMyTravel/TravelTeam.tsx
  src/components/manageMyTravel/UserStatusWaiting.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/constants/modalId.ts
  src/hooks/query/usePatchUserStatus.ts
  src/main.tsx
  src/pages/ManageMyTravel.tsx
  src/types/travelDataType.ts
Labels: feat

#173 [Feature] 함께 떠나요 글작성 완료 후 데이터 리셋
  src/api/addTravel/createTravel.ts
  src/components/addTravel/ChoiceTags.tsx
  src/components/addTravel/FloatingMenu.tsx
  src/components/addTravel/Thumbnail.tsx
  src/components/findGuideList/GuideCard.tsx
  src/components/traveList/TravelCard.tsx
  src/data/guideCardMockData.ts
  src/data/travelCardMockData.ts
  src/hooks/custom/useHandleAddTravel.ts
  src/hooks/custom/useResetAddTravel.ts
  src/hooks/query/useCreateTravel.ts
  src/pages/AddTravel.tsx
  src/pages/FindGuideList.tsx
  src/pages/Home.tsx
  src/routes/router.tsx
  src/stores/useAddTravelStore.ts
  src/stores/useSectionsStore.ts
  src/types/guideCardType.ts
  src/types/travelCardType.ts
  src/utils/validCheck.ts
Labels: feat

#176 [Fix] Rating.tsx #157
  src/components/Rating.tsx
  src/utils/validCheck.ts
Labels: fix

#177 [Feat] 가이드 구해요 글 작성 api 연동 및 이미지 업로드 api 수정
  src/api/addForFindGuide/postForFindGuide.ts
  src/api/addTravel/getImageUrls.ts
  src/components/addTravel/FloatingMenu.tsx
  src/components/addTravel/Introduction.tsx
  src/components/addTravel/ScheduleTeam.tsx
  src/components/addTravel/Thumbnail.tsx
  src/hooks/custom/useHandleAddTravel.ts
  src/hooks/custom/useHandleImageUpload.tsx
  src/hooks/custom/useResetAddTravel.ts
  src/hooks/query/useGetImageUrls.ts
  src/hooks/query/usePostForFindGuide.ts
  src/pages/AddForFindGuide.tsx
  src/pages/AddTravel.tsx
  src/stores/useFieldStore.ts
  src/stores/useImageStore.ts
  src/types/guideFindDataType.ts
  src/utils/prepareImageUpload.ts
  src/utils/updateDataValidate.ts
Labels: feat, fix

#179 [Feat] 가이드구해요 상세페이지 작업
  src/api/findGuideDetail/getFindGuideDetail.ts
  src/api/findGuideDetail/postComment.ts
  src/components/GuideProfile.tsx
  src/components/Profile.tsx
  src/components/addTravel/FloatingMenu.tsx
  src/components/addTravel/Introduction.tsx
  src/components/detail/Introduction.tsx
  src/components/detail/Thumbnail.tsx
  src/components/detail/Title.tsx
  src/components/findGuideDetail/CommentContainer.tsx
  src/components/findGuideDetail/CommentList.tsx
  src/components/findGuideDetail/WritingComment.tsx
  src/components/myReview/ReviewCard.tsx
  src/components/travelDetail/SideBar.tsx
  src/constants/queyKey.ts
  src/constants/url.ts
  src/hooks/query/useGetFindGuideDetail.ts
  src/hooks/query/usePostComment.ts
  src/pages/AddForFindGuide.tsx
  src/pages/FindGuideDetail.tsx
  src/routes/router.tsx
  src/types/guideFindDataType.ts
Labels: feat, fix

#182 [fix] server url 상수로 통일
  src/api/addForFindGuide/postForFindGuide.ts
  src/api/addTravel/createTravel.ts
  src/api/addTravel/getImageUrls.ts
  src/api/manageTravel/getManageTravel.ts
  src/api/manageTravel/getManageTravelTeams.ts
  src/api/manageTravel/patchUserStatus.ts
  src/api/myAccount/updateProfile.ts
  src/api/myCreatedTravel/getMycreatedTravel.ts
  src/api/myCreatedTravel/updateTravelActiveStatus.ts
  src/api/myJoinedTravel/getMyJoinedTravel.ts
  src/api/travelDetail/getTravelDetail.ts
  src/api/travelDetail/updateBookmark.ts
  src/layouts/Auth.tsx
  src/pages/Home.tsx
Labels: fix

#183 [Feat] 댓글 수정, 삭제 기능 추가
  src/api/findGuideDetail/deleteComment.ts
  src/api/findGuideDetail/patchComment.ts
  src/api/findGuideDetail/postComment.ts
  src/components/findGuideDetail/CommentContainer.tsx
  src/components/findGuideDetail/CommentList.tsx
  src/components/findGuideDetail/WritingComment.tsx
  src/constants/modalId.ts
  src/hooks/query/useDeleteComment.ts
  src/hooks/query/usePatchComment.ts
  src/pages/FindGuideDetail.tsx
Labels: feat

#186 [Fix] 댓글 api 추가 및 수정, 페이지네이션 기능 추가
  src/api/findGuideDetail/getCommentList.ts
  src/components/findGuideDetail/CommentContainer.tsx
  src/components/findGuideDetail/CommentList.tsx
  src/constants/countPerPage.ts
  src/constants/queyKey.ts
  src/hooks/query/useDeleteComment.ts
  src/hooks/query/useGetCommentList.ts
  src/hooks/query/usePatchComment.ts
  src/hooks/query/usePostComment.ts
  src/pages/FindGuideDetail.tsx
  src/types/guideFindDataType.ts
Labels: feat, fix

#188 [Rename] queryKey 파일명 오타 수정
  src/constants/queryKey.ts
  src/hooks/query/useDeleteComment.ts
  src/hooks/query/useGetCommentList.ts
  src/hooks/query/useGetFindGuideDetail.ts
  src/hooks/query/useGetManageTravel.ts
  src/hooks/query/useGetManageTravelTeams.ts
  src/hooks/query/useGetMyCreatedTravel.ts
  src/hooks/query/useGetMyJoinedTravel.ts
  src/hooks/query/useGetTravelDetail.ts
  src/hooks/query/usePatchComment.ts
  src/hooks/query/usePatchUserStatus.ts
  src/hooks/query/usePostComment.ts
  src/hooks/query/useUpdateBookmark.ts
  src/hooks/query/useUpdateTravelStatus.ts
  src/pages/Home.tsx
Labels: rename

#189 [Feat] 가이드구해요 사이드에 작성자 정보 추가
  src/components/GuideProfile.tsx
  src/components/findGuideDetail/SideBar.tsx
  src/pages/FindGuideDetail.tsx
  src/types/guideFindDataType.ts
Labels: feat, fix

#191 [Feat] introduction 컴포넌트 dompurify 적용
  package-lock.json
  package.json
  src/components/detail/Introduction.tsx
  src/components/findGuideDetail/CommentContainer.tsx
  src/types/guideFindDataType.ts
Labels: feat

#192 [Feat]리스트 api 연동 및 무한스크롤 적용
  src/api/guideList/getGuideList.ts
  src/api/travelList/getTravelList.ts
  src/components/TagCardWrap.tsx
  src/components/findGuideList/GuideCard.tsx
  src/hooks/query/useGetGuideList.ts
  src/hooks/query/useGetTravelList.ts
  src/layouts/Breadcrumb.tsx
  src/pages/FindGuideList.tsx
  src/pages/Home.tsx
  src/pages/TravelList.tsx
Labels: feat

#193 [Feat] 계좌번호 api 연동
  src/api/myAccount/updateAccountNumber.ts
  src/components/myPage/MyBankAccount.tsx
  src/hooks/query/useUpdateAccountNumber.ts
  src/hooks/query/useUpdateProfile.ts
  src/pages/MyAccount.tsx
  src/routes/router.tsx
  src/types/userType.ts
Labels: feat

#195 [Bug] 북마크 상태업데이트 오류해결 및 예외처리 추가
  src/api/travelDetail/getTravelDetail.ts
  src/components/GrayBack.tsx
  src/components/addTravel/Course.tsx
  src/components/addTravel/ScheduleTeam.tsx
  src/components/detail/Introduction.tsx
  src/components/detail/Title.tsx
  src/components/travelDetail/Application.tsx
  src/components/travelDetail/TravelInformation.tsx
  src/hooks/query/useGetTravelDetail.ts
  src/hooks/query/useUpdateBookmark.ts
  src/pages/TravelDetail.tsx
Labels: fix, bug

#201 [feat] 프로필 수정 취소 기능
  src/pages/MyAccount.tsx
Labels: feat

#202 [feat] 내가 참여한 여행 없을 경우에 대한 처리
  src/components/myTravel/MyJoinedContent.tsx
  src/components/myTravel/MyTravelContent.tsx
Labels: feat

#203 [Feature] 북마크 api연동
  src/api/bookmark/getBookmarkList.ts
  src/api/home/getHomeGuideList.ts
  src/api/home/getHomeTravelList.ts
  src/api/travelList/getTravelList.ts
  src/components/traveList/TravelCard.tsx
  src/constants/queryKey.ts
  src/hooks/query/useGetBookmarkList.ts
  src/hooks/query/useGetHomeList.ts
  src/hooks/query/useGetTravelList.ts
  src/pages/Bookmark.tsx
  src/pages/Home.tsx
Labels: feat

#204 [Fix]사이드바 및 내여행-tab관련 수정
  src/components/myPage/MyPageSideMenu.tsx
  src/components/myTravel/MyTravelTab.tsx
  src/hooks/query/useUpdateAccountNumber.ts
  src/pages/MyAccount.tsx
Labels: fix

#206 [Fix] firebase hosting settings
  .github/workflows/firebase-hosting-merge.yml
Labels: fix

#207 [Feat] 내가 만든 여행 삭제
  src/api/manageTravel/deleteTravel.ts
  src/components/manageMyTravel/TravelManageHeader.tsx
  src/hooks/query/useDeleteTravel.ts
Labels: feat

#209 [Feat]관리 페이지 이동 기능
  src/components/myTravel/MyTravelCard.tsx
  src/pages/MyCreatedTravel.tsx
Labels: feat

#212 [Fix] 리뷰 모달 수정, 내가 참여한 여행에서 버튼 누를시 리뷰 모달 활성화
  src/components/GuideProfile.tsx
  src/components/myReview/ReviewWriteModal.tsx
  src/components/myTravel/MyJoinedContent.tsx
  src/types/myJoinedTravel.ts
Labels: fix

#211 [Feat]내가 만든여행, 내가 참여한 여행 무한스크롤 적용
  src/api/myCreatedTravel/getMycreatedTravel.ts
  src/api/myJoinedTravel/getMyJoinedTravel.ts
  src/components/myTravel/MyJoinedContent.tsx
  src/components/myTravel/MyTravelContent.tsx
  src/hooks/query/useGetMyCreatedTravel.ts
  src/hooks/query/useGetMyJoinedTravel.ts
  src/pages/TravelList.tsx
Labels: feat

#215 [Fix] 여행 글쓰기에서 이미지 업로드 오류/ 이미지 리랜더 오류
  src/api/addTravel/getImageUrl.ts
  src/components/addTravel/Introduction.tsx
  src/components/addTravel/Thumbnail.tsx
  src/hooks/query/useGetImageUrl.ts
  src/utils/prepareImageUpload.ts
Labels: fix

#213 [Feat] 리뷰 작성 API 연동
  src/api/review/createReview.ts
  src/api/review/getReviewsByUserId.ts
  src/components/Rating.tsx
  src/components/myReview/ReviewCard.tsx
  src/components/myReview/ReviewWriteModal.tsx
  src/components/myTravel/MyJoinedContent.tsx
  src/constants/queryKey.ts
  src/constants/reviewConstant.ts
  src/hooks/query/useCreateReview.ts
  src/hooks/query/useGetReviews.ts
  src/pages/MyReviews.tsx
  src/types/myJoinedTravel.ts
  src/types/reviewType.ts
Labels: fix
