Repository resistance2/travely, pull requests merged in 2025-02, with the labels that each got.

#218 [Feat] 리뷰 삭제 기능 구현, 리뷰 컴포넌트 스타일 수정
  src/api/review/deleteReview.ts
  src/components/ConfirmModal.tsx
  src/components/DeleteIcon.tsx
  src/components/myReview/ReviewCard.tsx
  src/hooks/query/useDeleteReview.ts
  src/types/reviewType.ts
Labels: feat

#219 [Fix] floating menu
  src/components/addTravel/FloatingMenu.tsx
Labels: fix

#221 [feat]여행이 날짜가 지났을때와 지나지 않았을 때에 대한 예약상태 표시 처리
  src/components/myTravel/MyJoinedContent.tsx
Labels: feat

#223 [Fix] 여행글 작성시 기존 글 내용 초기화, 가이드 구해요 글 작성시 쿼리키 무효화
  src/api/travelDetail/registerTravel.ts
  src/components/FiledBtn.tsx
  src/components/Team.tsx
  src/components/detail/SideTravelTeam.tsx
  src/components/findGuideList/GuideCard.tsx
  src/components/manageMyTravel/TravelTeam.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/components/myFindGuide/FindGuideCard.tsx
  src/components/myTravel/MyJoinedContent.tsx
  src/components/myTravel/MyTravelContent.tsx
  src/components/travelDetail/Application.tsx
  src/components/travelDetail/SideBar.tsx
  src/constants/queryKey.ts
  src/hooks/custom/useResetAddTravel.ts
  src/hooks/query/useGetGuideList.ts
  src/hooks/query/usePostForFindGuide.ts
  src/hooks/query/useRegisterTravel.ts
  src/pages/AddForFindGuide.tsx
  src/pages/AddTravel.tsx
  src/pages/ManageMyTravel.tsx
  src/types/travelDataType.ts
Labels: fix

#224 [Fix] 유저 프로필이 없을 때 기본 이미지로 나오게함
  src/components/Team.tsx
  src/layouts/Auth.tsx
  src/pages/MyAccount.tsx
Labels: fix

#225 Feat: 승인을 기다리는 여행자수를 확인할수 있게함.
  src/api/manageTravel/getTravelersWaitingCount.ts
  src/components/Profile.tsx
  src/components/manageMyTravel/UserTable.tsx
  src/constants/queryKey.ts
  src/hooks/query/useTravelersWaitingCount.ts
  src/layouts/Auth.tsx
Labels: feat

#227 [feat]내 계정 페이지 내에 유저별점 추가
  src/layouts/Auth.tsx
  src/pages/MyAccount.tsx
  src/types/userType.ts
Labels: feat

#229 Fix: alert 메시지를 toast로 교체, 여행글 작성후 travel-list쿼리키 무효화 #228
  src/components/addTravel/ChoiceTags.tsx
  src/components/addTravel/FloatingMenu.tsx
  src/components/addTravel/ScheduleTeam.tsx
  src/components/myReview/ReviewWriteModal.tsx
  src/hooks/custom/useHandleAddTravel.ts
  src/hooks/custom/useUploadTravelImages.ts
  src/hooks/query/useCreateTravel.ts
  src/layouts/Auth.tsx
  src/pages/AddTravel.tsx
  src/pages/TravelList.tsx
  src/stores/useAddTravelStore.ts
  src/types/travelDataType.ts
  src/utils/validCheck.ts
Labels: fix

#232 [Fix] 기간이 지난 여행 신청 막기
  src/components/travelDetail/Application.tsx
Labels: fix

#234 [Fix] 가이드 구해요 페이지 페이지네이션 로직 수정, quillnote.css import 수정, axios 함수들 수정
  src/api/bookmark/getBookmarkList.ts
  src/api/findGuideDetail/getCommentList.ts
  src/api/guideList/getGuideList.ts
  src/api/home/getHomeGuideList.ts
  src/api/home/getHomeTravelList.ts
  src/components/addTravel/Introduction.tsx
  src/pages/FindGuideList.tsx
Labels: fix

#235 [Fix] api 호출 함수들 수정, get api를 호출시 query params가 undefined나 null이 되지 않도록함
  src/api/bookmark/addBookmark.ts
  src/api/bookmark/deleteBookmark.ts
  src/api/bookmark/getBookmarkList.ts
  src/api/manageTravel/getManageTravelTeams.ts
  src/api/myCreatedTravel/getMycreatedTravel.ts
  src/api/myJoinedTravel/getMyJoinedTravel.ts
  src/api/travelDetail/getTravelDetail.ts
  src/components/manageMyTravel/TravelManageHeader.tsx
  src/hooks/query/useDeleteTravel.ts
  src/hooks/query/usePatchUserStatus.ts
  src/hooks/query/useTravelersWaitingCount.ts
  src/hooks/query/useUpdateBookmark.ts
  src/pages/Bookmark.tsx
Labels: fix

#236 [Fix] waitingBadgeCount가 나오게 수정함
  src/components/myTravel/MyTravelContent.tsx
  src/types/myCreatedTravelType.ts
Labels: fix

#237 [Fix] 여행카드 제목 클릭 시 해당 여행 글로 이동, 여행 글 작성 페이지에서 각 입력 컴포넌트 간의 여백 수정
  src/components/GrayBack.tsx
  src/components/myTravel/MyTravelCard.tsx
  src/components/myTravel/MyTravelContent.tsx
  src/pages/FindGuideList.tsx
Labels: fix

#238 [Feat] 내가 만든 여행(가이드 구해요 여행글 페이지) 구현
  src/api/myCreatedTravel/getCreatedGuideTravel.ts
  src/components/myFindGuide/FindGuideCard.tsx
  src/components/myFindGuide/FindGuideContent.tsx
  src/data/guideCardMockData.ts
  src/hooks/query/useGetMyCreatedGuideTravel.ts
  src/types/guideCardType.ts
Labels: feat, fix

#240 [Feat]내가 참여한 여행 제목 클릭시 해당여행 상세페이지로 이동
  src/components/myTravel/MyJoinedContent.tsx
  src/pages/MyAccount.tsx
Labels: feat

#243 [Fix] 관리페이지 여행일정이 있음에도 없다는 문구 뜨는 오류 해결
  src/components/manageMyTravel/TravelTeam.tsx
  src/components/manageMyTravel/UserTable.tsx
Labels: fix

#242 [Fix] 리뷰, 가이드 여행 리스트 api 호출 오류 수정
  src/hooks/query/useGetMyCreatedGuideTravel.ts
  src/hooks/query/useGetReviews.ts
Labels: fix
